sample_launch_request:
	curl -H "Content-Type: application/json" -X POST \
		-d @sample_launch_request.json \
		http://localhost:8080/api/v1/alexa/skill

sample_intent_request:
	curl -H "Content-Type: application/json" -X POST \
		-d @sample_intent_request.json \
		http://localhost:8080/api/v1/alexa/skill

sample_session_ended_request:
	curl -H "Content-Type: application/json" -X POST \
		-d @sample_session_ended_request.json \
		http://localhost:8080/api/v1/alexa/skill
